### ISSUE TITLE
interpolation and marker filling

### ISSUE THREAD

**Issue by halilSozen** [alchemyst/ternplot#11]
Dear Carl,

First of all thanks for sharing such a great code. 

I am quite beginner in MATLAB and I have 2 questions regarding your code. 

I am using your code to plot ternary phase diagram based on some ab initio based formation energies. You can see my phase diagram in here:
![fig1](https://user-images.githubusercontent.com/33554333/33789501-1efa41e8-dc79-11e7-8ea7-9f2c7144e251.png)

Here is my questions:

1. I want to use linear interpolation in between entered values. As I know it is cubic, right ? So I have changed the zg = griddata(x, y, Z, xg, yg, 'v4') in ternsurf.m file (simply v4 -->linear). So is that enough to have linear interpolation ? Once I did that modification I got the image in here (2D): 
![fig2](https://user-images.githubusercontent.com/33554333/33789576-cab14392-dc79-11e7-9b13-4da7973eb60e.png)

Also 3D version seen in here:
![fig3](https://user-images.githubusercontent.com/33554333/33789581-d738592a-dc79-11e7-8177-08b8c0d6c269.png)

If that modification I did is correct for the linear interpolation, could you please tell me how can I plot in proper way in 2D, like the first image ?

2. As you see in first image the markers are not filled. Once I used the "filled" option they filled with black color. Can we filled the markers corresponding energy color in the colorbar ? Because the most correct value is what we enter and rest is interpolation so I need to make that markers filled with corresponding energy colors in the colorbar. Is that possible ?

**Comment by alchemyst** [comment]
Thank you for your detailed report. Regarding the first issue with the "holes" in the plot: The issue appears to lie with `griddata`. I don't have a simple solution at this point for providing linear interpolation. The only interpolation which reliably doesn't produce these "holes" is `v4`. 

Regarding the markers, you can use `terncoords` to find the x, y coordinates of the points you have, then use `scatter3` with the `c` argument to get the markers in the colors you want.
